bbs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from django.views.static import serve
from django.conf import settings




urlpatterns = [
    url(r'^admin/', admin.site.urls),  #chen,密码：chen1111
    url(r'^blog/',include('blog.urls')),
    url(r'^login',views.login),
    url(r'^logout',views.logout),
    url(r'^verification_code',views.verification_code),
    url(r'^register',views.register),
    url(r'^index',views.index),
    url(r'^check_user',views.check_user),
    # media相关的路由设置
    url(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),

]

blog/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息表
    """
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png", verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)

    blog = models.OneToOneField(to="Blog", to_field="nid", null=True)

    def __str__(self):
        return self.username
    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)  # 个人博客标题
    site = models.CharField(max_length=32, unique=True)  # 个人博客后缀
    theme = models.CharField(max_length=32)  # 博客主题

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "博客"
        verbose_name_plural = verbose_name


class Category(models.Model):
    """
    个人博客文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 分类标题
    blog = models.ForeignKey(to="Blog", to_field="nid")  # 外键关联博客，一个博客站点可以有多个分类

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    标签
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 标签名
    blog = models.ForeignKey(to="Blog", to_field="nid")  # 所属博客

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    """
    文章
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50,verbose_name="文章标题")  # 文章标题
    desc = models.CharField(max_length=255)  # 文章描述
    create_time = models.DateTimeField()  # 创建时间
    #评论
    comment_count = models.IntegerField(verbose_name="评论数",default=0)
    #点赞数
    up_count = models.IntegerField(verbose_name="点赞数",default=0)
    #踩
    down_count = models.IntegerField(verbose_name="踩数",default=0)

    category = models.ForeignKey(to="Category", to_field="nid", null=True)
    user = models.ForeignKey(to="UserInfo", to_field="nid")
    tags = models.ManyToManyField(  # 中介模型
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag"),  # 注意顺序！！！
    )

    def __str__(self):
        return self.title


class ArticleDetail(models.Model):
    """
    文章详情表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to="Article", to_field="nid")


class Article2Tag(models.Model):
    """
    文章和标签的多对多关系表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid")
    tag = models.ForeignKey(to="Tag", to_field="nid")
    #在admin中更改标题
    def __str__(self):
        return "{}---{}".format(self.article.title,self.tag.title)

    class Meta:
        unique_together = (("article", "tag"),)


class ArticleUpDown(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", null=True)
    article = models.ForeignKey(to="Article", null=True)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = (("article", "user"),)


class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid")
    user = models.ForeignKey(to="UserInfo", to_field="nid")
    content = models.CharField(max_length=255)  # 评论内容
    create_time = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey("self", null=True,blank=True)#blank为True意思在django.admin中可以不填这个字段

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "用户信息"  #改写表的名字为中文
        verbose_name_plural = verbose_name #去掉名字后面的s

blog/forms.py
from django.shortcuts import render,redirect,HttpResponse
from django import forms
from django.forms import widgets
from blog import models
from django.core.exceptions import ValidationError

class RegForm(forms.Form):
    username = forms.CharField(
        max_length=24,
        label='用户名',
        widget=widgets.TextInput(attrs={"class":"form-control"}),
        error_messages={
            'max_length':'用户名不能大于24位',
            'required':'用户名不能为空',
        }

    )

    password = forms.CharField(
        max_length=6,
        label='密码',
        widget=widgets.PasswordInput(attrs={"class":"form-control"}),
        error_messages={
            'min_length':'密码至少六位',
            'required':'密码不能为空',
        }
    )

    re_password = forms.CharField(
        max_length=6,
        label='确认密码',
        widget=widgets.PasswordInput(attrs={"class":"form-control"}),
        error_messages={
            'min_length': '密码至少六位',
            'required': '密码不能为空',
        }
    )

    email = forms.EmailField(
        label='邮箱',
        widget=widgets.EmailInput(attrs={"class":"form-control"}),
        error_messages = {
            'invalid':'邮箱格式不正确',
            'required': '邮箱不能为空',
        }
    )
    # 用内置form判断用户名邮箱是否存在
    #重写username钩子函数，判断用户名是否注册
    # def clean_username(self):
    #     username = self.cleaned_data.get("username")
    #     user_exist = models.UserInfo.objects.filter(username=username).first()
    #     if user_exist:
    #         self.add_error("username",ValidationError("用户名已注册"))
    #     else:
    #         return username
    # 重写email钩子函数，判断邮箱是否注册
    def clean_email(self):
        email = self.cleaned_data.get("email")
        email_exist = models.UserInfo.objects.filter(email=email).first()
        if email_exist:
            self.add_error("email",ValidationError("邮箱已注册"))
        else:
            return email
    # 重写全局的钩子函数,判断输入密码是否一致
    def clean(self):
        password = self.cleaned_data.get('password')
        re_password = self.cleaned_data.get('re_password')
        if password != re_password:
            self.add_error('re_password',ValidationError('密码不一致'))
            raise ValidationError('密码不一致')
        return self.cleaned_data

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
    <link rel="stylesheet" href="/static/theme/{{ user.blog.theme }}">
    <script src="/static/jquery-3.3.1.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>

<div class="header"><h3 >{{ user.blog.title }}</h3></div>

<div class="container ">
    <div class="row">
        <div class="col-md-3">
            {% load my_tags %}
            {% get_left username %}


        </div>
        <div class="col-md-8">
            {% block page_main %}
            {% endblock %}


        </div>

    </div>
</div>

</body>
</html>

templates/category_list.html
{% extends "base.html" %}
{% block page_main %}
              <div class="article-list">

                {% for article in category_article %}
                    <div class="article">
                        <p class="article-title"><a href="/blog/{{ article.user.username }}/article/{{ article.pk }}/">{{ article.title }}</a></p>
                        <div class="media">
                            <div class="media-left">

                                <a href="#">
                                    <img class="media-object author-img" src="/media/{{ article.user.avatar }}/"
                                         alt="...">
                                </a>
                            </div>
                            <div class="media-body">


                                <p>{{ article.desc }}</p>

                            </div>
                        </div>
                        <div class="article-footer">
                            <span>{{ article.user.username }}</span>发布于
                            <span>{{ article.create_time|date:'Y-M-D H:i:s' }}</span>
                            <span class="glyphicon glyphicon-comment">评论数({{ article.comment_set.all.count }})</span>
                            <span class="glyphicon glyphicon-thumbs-up">点赞数({{ article.articleupdown_set.all.count }})</span>
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            </div>


{% endblock %}

templates/detail.html
{% extends "base.html" %}
{% block page_main %}
    <div class="article-detail">
        <h1>{{ article.title }}</h1>
        <p>{{ article.articledetail.content|safe }}</p>


    </div>
    <div class="poll clearfix">
        <div id="div_digg">
            <div class="diggit action">
                <span class="diggnum" id="digg_count">{{ article.up_count }}</span>
            </div>
            <div class="buryit action">
                <span class="burynum" id="bury_count">{{ article.down_count }}</span>
            </div>
            <div class="clear"></div>
            <div class="diggword" id="digg_tips"></div>

        </div>
    </div>

    <p>评论树</p>
    <div class="comment_tree"></div>



    <div class="info" article_id="{{ article.pk }}" username="{{ request.user.username }}"></div>
    {% csrf_token %}
    <p>评论列表:</p>
    <ul class="comment-list">
        {% for comment in comment_list %}
        <li class="list-group-item">
            <div><a href="">#{{ forloop.counter }}楼</a> &nbsp;&nbsp;
                <a href="">{{ comment.user.username }}</a>&nbsp;&nbsp;
                <span>{{ comment.create_time|date:"Y-m-d H:m" }}</span>
                {% if request.user.username ==  comment.user.username  %}
                <a href="" class="pull-right">删除</a>
                    {% else %}
                    <a class="pull-right reply" username="{{ comment.user.username }}" comment_pk="{{ comment.pk }}">回复</a>
                {% endif %}

            </div>
        {% if comment.parent_comment_id %}
        <div class="pid_info well">
            <p>{{ comment.parent_comment.user.username }}:&nbsp;&nbsp;{{ comment.parent_comment.content }}</p>
        </div>
        {% endif %}
            <div class="con"><p>{{ comment.content }}</p></div>
        </li>
    {% endfor %}
    </ul>


    {% if request.user.username %}
        <div>
            <p>发表评论</p>
            <p>
                昵称：<input type="text" class="author" disabled="disabled" size="50" value="{{ request.user.username }}">
            </p>
            <p>评论内容：</p>
            <textarea name="" id="comment-content" cols="60" rows="10"></textarea>
            <p>
                <button class="comment-btn">提交评论</button>
            </p>
        </div>
    {% else %}
        <a href="/login/">登录</a>
    {% endif %}

    <script src="/static/up_down.js"></script>
    <script>
    $(function () {
        //获取评论树信息
        $.ajax({
            url:"blog/comment_tree/"+'{{ article.pk }}/',
            success:function (data) {
                console.log(data);
                $.each(data,function (index,comment_dict) {
                    var s='<div class="comment_item" comment_id='+comment_dict.pk+'><span class="content">'+comment_dict.content+'</span></div>'
                    if(comment_dict.parent_comment_id){
                       //子评论
                        pid=comment_dict.parent_comment_id;
                        $("[comment_id="+pid+"]").append(s)
                    }
                    else{  //根评论

                        $(".comment_tree").append(s)

                    }
                })
            }
        });








        {#提交评论#}
        var pid="";
        $(".comment-btn").click(function () {
            var article_id = $(".info").attr("article_id");
            var content = $("#comment-content").val();
            if (pid){
                var index = content.indexOf("\n");
                var content = content.slice(index+1);

            }


            $.ajax({
                url:"/blog/comment/",
                type:"post",
                data:{
                    article_id:article_id,
                    content:content,
                    pid:pid,
                    csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                },
                    success:function (data) {

                        var create_time = data.create_time;
                        var content = data.content;
                        var username = data.username;
                        var li = '<li class="list-group-item"> <div><a href="">#{{ forloop.counter }}楼</a> &nbsp;&nbsp; <a href="">'+username+'</a>&nbsp;&nbsp; <span>'+create_time+'</span> <a href="" class="pull-right">删除</a> </div> <div class="con"><p>'+content+'</p></div> </li>'
                        console.log("oooook");
                        $(".comment-list").append(li);
                        $("#comment-content").val("")
                        pid="";


                    }

            })

        });
        {#回复按钮#}
        $(".reply").click(function () {
            var user_reply = "@"+$(this).attr("username")+"\n";

            $("#comment-content").val(user_reply);
            $("#comment-content").focus();

            {#pid赋值;#}
            pid = $(this).attr("comment_pk");




        })



    })
    </script>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block page_main %}
              <div class="article-list">

                {% for article in article_list %}
                    <div class="article">
                        <p class="article-title"><a href="/blog/{{ article.user.username }}/article/{{ article.pk }}/">{{ article.title }}</a></p>
                        <div class="media">
                            <div class="media-left">

                                <a href="#">
                                    <img class="media-object author-img" src="/media/{{ article.user.avatar }}/"
                                         alt="...">
                                </a>
                            </div>
                            <div class="media-body">


                                <p>{{ article.desc }}</p>

                            </div>
                        </div>
                        <div class="article-footer">
                            <span>{{ article.user.username }}</span>发布于
                            <span>{{ article.create_time|date:'Y-M-D H:i:s' }}</span>
                            <span class="glyphicon glyphicon-comment">评论数({{ article.comment_set.all.count }})</span>
                            <span class="glyphicon glyphicon-thumbs-up">点赞数({{ article.articleupdown_set.all.count }})</span>
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            </div>


{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">

</head>
<body>


<div class="container">
    <div class="row">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">CH-Blog</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                        <li><a href="#">Link</a></li>

                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if request.user.username %}
                            <li><a href="#">{{ request.user.username }}</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-haspopup="true"
                                   aria-expanded="false">Dropdown <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="/logout/">注销</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="/login/">登录</a></li>
                            <li><a href="/register/">注册</a></li>

                        {% endif %}
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-success">
                <div class="panel-heading">左侧一</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">左侧一</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="article-list">

                {% for article in article_list %}
                    <div class="article">
                        <h4><a href="/blog/{{ article.user.username }}/article/{{ article.pk }}/">{{ article.title }}</a></h4>
                        <div class="media">
                            <div class="media-left">

                                <a href="#">
                                    <img class="media-object author-img" src="/media/{{ article.user.avatar }}/"
                                         alt="...">
                                </a>
                            </div>
                            <div class="media-body">


                                <p>{{ article.desc }}</p>

                            </div>
                        </div>
                        <div class="article-footer">
                            <span><a href="/blog/{{ article.user.username }}">{{ article.user.username }}</a></span>发布于
                            <span>{{ article.create_time|date:'Y-M-D H:i:s' }}</span>
                            <span class="glyphicon glyphicon-comment">评论数({{ article.comment_set.all.count }})</span>
                            <span class="glyphicon glyphicon-thumbs-up">点赞数({{ article.articleupdown_set.all.count }})</span>
                        </div>
                    </div>
                {% endfor %}
            </div>


        </div>
        <div class="col-md-2">
            <div class="panel panel-success">
                <div class="panel-heading">左侧一</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">左侧一</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/left_menu.html
<div class="panel panel-default">
    <div class="panel-heading">文章分类</div>
    <div class="panel-body">
        {#                    {% for category in user.blog.category_set.all %}#}
        {#                    <div><a href="">{{ category.title }}({{  category.article_set.all.count }})</a></div>#}
        {#                    {% endfor %}#}
        {% for category in category_list %}
            <div><a href="/blog/{{ user.username }}/{{ category.title }}/">{{ category.title }}({{ category.c }})</a></div>
        {% endfor %}
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">文章标签</div>
    <div class="panel-body">
        {% for tag in tag_list %}
            <div><a href="">{{ tag.title }}({{ tag.c }})</a></div>
        {% endfor %}

    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">日期分类</div>
    <div class="panel-body">
        {% for archive in archive_list %}
            <div><a href="">{{ archive.archive_ym }}({{ archive.c }})</a></div>
        {% endfor %}

    </div>
</div>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
    <script src="/static/jquery-3.3.1.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <script>
        $(function () {
            $("#id_avatar").change(function () {
                // 1. 创建一个读取文件的对象
                var fileReader = new FileReader();
                // 取到当前选中的头像文件
                // console.log(this.files[0]);
                // 读取你选中的那个文件
                fileReader.readAsDataURL(this.files[0]);  // 读取文件是需要时间的
                fileReader.onload = function () {
                    // 2. 等上一步读完文件之后才 把图片加载到img标签中
                    $("#avatar-img").attr("src", fileReader.result);
                }
            });

        });
        $(function () {
            $("#reg_btn").click(function () {
                {#alert(8888)#}
                {#var username = $("#id_username").val();#}
                {#var password = $("#id_password").val();#}
                {#var re_password = $("#id_re_password").val();#}
                {#var email = $("#id_email").val();#}
                {#提交含文件类型的，要用FormData()#}
                var formData = new FormData();
                formData.append("username",$("#id_username").val());
                formData.append("password",$("#id_password").val());
                formData.append("re_password",$("#id_re_password").val());
                formData.append("email",$("#id_email").val());
                formData.append("avatar",$("#id_avatar")[0].files[0]);
                formData.append("csrfmiddlewaretoken",$("[name='csrfmiddlewaretoken']").val());
                $.ajax({
                    url:"/register/",
                    type:"post",
                    processData:false,
                    contentType:false,
                    data:formData,
                    {#data:{#}
                    {#    "username":username,#}
                    {#    "password":password,#}
                    {#    "re_password":re_password,#}
                    {#    "email":email,#}
                    {#    "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val()#}
                    {#{,#}
                    success:function (data) {
                        {#alert(000);#}
                        if(data.status ){
                            {#alert(7777);#}
                            console.log(data.msg);
                            $.each(data.msg,function (k,v) {
                                console.log(k,v[0]);
                                console.log($("#id_"+k));
                                $("#id_"+k).next().text(v[0]).parent().parent().addClass("has-error");
                            })

                        }else{
                            location.href = data.msg;
                        }
                    }
                })
            })
        });
        {##所有input绑定焦点时间,来取消他的错误显示和class样式#}
        $(function () {
            $("form input").focus(function () {

                $(this).next().text("").parent().parent().removeClass("has-error");
            })
        });

        $(function () {
            $("#id_username").blur(function () {
                {#alert(00)#}
                var username = $(this).val();
                {#alert(username);#}
                $.ajax({
                    url:"/check_user/",
                    type:"get",
                    data:{"username":username},
                    success:function (data) {
                        {#alert(data.count)#}
                        if(data.count){
                            $("#id_username").next().text("用户名已存在").parent().parent().addClass("has-error");
                        }

                    }

                })

            })

        })


    </script>

</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="/register/" method="post" class="form-horizontal reg-form" novalidate enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ reform_obj.username.id_for_label }}"
                           class="col-sm-2 control-label">{{ reform_obj.username.label }}</label>
                    <div class="col-sm-10">
                        {{ reform_obj.username }}
                        <span id="helpBlock2" class="help-block">{{ reform_obj.username.errors.0 }}</span>
                    </div>

                </div>
                <div class="form-group">
                    <label for="{{ reform_obj.password.id_for_label }}"
                           class="col-sm-2 control-label">{{ reform_obj.password.label }}</label>
                    <div class="col-sm-10">
                        {{ reform_obj.password }}
                        <span id="helpBlock2" class="help-block">{{ reform_obj.password.errors.0 }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ reform_obj.re_password.id_for_label }}"
                           class="col-sm-2 control-label">{{ reform_obj.re_password.label }}</label>
                    <div class="col-sm-10">
                        {{ reform_obj.re_password }}
                        <span id="helpBlock2" class="help-block">{{ reform_obj.re_password.errors.0 }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ reform_obj.email.id_for_label }}"
                           class="col-sm-2 control-label">{{ reform_obj.email.label }}</label>
                    <div class="col-sm-10">
                        {{ reform_obj.email }}
                        <span id="helpBlock2" class="help-block">{{ reform_obj.email.errors.0 }}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">头像</label>
                    <div class="col-sm-10">
                        <label for="id_avatar" class="col-sm-2 control-label"><img id="avatar-img" src="/static/img/tt.png" alt=""></label>
                        <input type="file" id="id_avatar" name="avatar" style="display: none">
                        <span id="helpBlock2" class="help-block"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="button" class="btn btn-default btn-success" id="reg_btn">注册</button>
                        <span id="helpBlock2" class="help-block"></span>
                    </div>
                </div>
            </form>

        </div>

    </div>
</div>

</body>
</html>